Install SPI and regular bootstream to /lib/modules/ of the SD card

diff --git a/install_hdr_mod b/install_hdr_mod
--- a/install_hdr_mod
+++ b/install_hdr_mod
@@ -35,5 +35,14 @@ sudo mount /dev/$1 mount_point/ &&\
     exit 1
   fi
 )
+(
+  echo "Copying SPI and NAND bootstreams to device $1"
+  sudo -E cp imx-bootlets-src-10.12.01/imx28_ivt_linux.s* mount_point/lib/modules/
+  if [ $? -ne "0" ] ; then
+    echo "Failed to failed to copy bootstream files to device $1"
+    exit 1
+  fi
+)
+
 sudo umount mount_point
 rmdir mount_point
